# Generated by Django 5.1.4 on 2025-01-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_sig', models.IntegerField()),
                ('tipo_documento', models.CharField(max_length=20)),
                ('numero_documento', models.CharField(max_length=20)),
                ('numero_telefono', models.CharField(max_length=15)),
                ('operadora', models.CharField(max_length=20)),
                ('respuesta_bot', models.TextField()),
            ],
        ),
    ]
