# Generated by Django 5.1.4 on 2025-01-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botdata',
            old_name='id_sig',
            new_name='idsig',
        ),
        migrations.RenameField(
            model_name='botdata',
            old_name='numero_documento',
            new_name='numero_doc',
        ),
        migrations.RenameField(
            model_name='botdata',
            old_name='numero_telefono',
            new_name='numero_tele',
        ),
        migrations.RenameField(
            model_name='botdata',
            old_name='tipo_documento',
            new_name='tipo_doc',
        ),
    ]
